// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace lecture_9
{
    public partial class TblToDoList
    {
        public int Id { get; set; }
        public DateTime AddDate { get; set; }
        public string Title { get; set; }
        public bool IsDone { get; set; }
    }
}