// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace lecture_9
{
    public partial class TblErrorLogs
    {
        public long ExceptionId { get; set; }
        public string ExPath { get; set; }
        public string ExMsg { get; set; }
        public string ExStackTrace { get; set; }
        public string InnerExMsg { get; set; }
        public string InnerExStackTrace { get; set; }
        public DateTime ExDate { get; set; }
        public short? HttpErrorStatusCode { get; set; }
        public string HttpErrorPath { get; set; }
        public string HttpErrorRequest { get; set; }
        public string HttpErrorCookies { get; set; }
    }
}